### ISSUE TITLE
Dockerfile Exposes port 8000

### ISSUE THREAD

**Issue by duganth-va** [trallnag/prometheus-ecs-discoverer#6]
First, thanks for making this tool!

Second, I may be missing something, but image in Docker Hub exposes port 8000, should it be 8080? I couldn't see where 8000 was used with this utility. Thanks!

**Comment by trallnag** [comment]
Hey @duganth-va, thanks! Can you share where you see that the image is exposing port 8000?

Here is the image hosted: https://hub.docker.com/r/trallnag/prometheus_ecs_discoverer

And here is the Dockerfile: https://github.com/trallnag/prometheus-ecs-discoverer/blob/master/Dockerfile

So there shouldn't be any port exposed by default I assume.

**Comment by duganth-va** [comment]
So when I ran the app on ECS I pulled from docker hub, I saw the port 8000 exposed. I was a bit confused becauase the documentation was referencing 8080, so I looked at the file below and saw line 10. 

https://hub.docker.com/layers/trallnag/prometheus_ecs_discoverer/latest/images/sha256-b77a9dceba18eb1653b1e4cec8c97cbf999ae7323ef55b0ae693032ee68bed62

**Comment by trallnag** [comment]
Ah, interesting. So it's the parent image I'm using. If you are worried about this EXPOSE being unsafe, notice that there is a big difference between port mappings (for example with `-P` when you use `docker run`) and exposing ports. `EXPOSE` is really nothing more than a kind of meta data and it does not mean that this port is actually open.

I think EXPOSE was introduced a long time ago when linking Docker containers with `--link` was still a thing. Back then you would declare what ports should be available for the Docker own name resolution and other containers linked to the container could access it with `<container-name>:<exposed-port>`. But if you knew the concrete IP you could still access any port you like.

**Comment by duganth-va** [comment]
Great clarification on the differences and thank you! I think the biggest part was confusion more than anything, running `docker ps` I would see 8000 exposed (but not mapped to host). I was making sure I wasn't missing something.
