### ISSUE TITLE
Cross account ECS discovery

### ISSUE THREAD

**Issue by evelez-va** [trallnag/prometheus-ecs-discoverer#8]
Greetings,

I have a question regarding cross account discovery of ECS tasks. I have two AWS accounts (A and B). I have the prometheus-ecs-discoverer running on a docker container on an EC2 instance in account A, which has a role with the required policy for it to work. I have setup a role in account B, with the appropriate policy, so that the EC2 instance in account A can assume it. I added another policy to account A's EC2 instance role so that it can assume the role I created in account B.  When I run the service on the container in account A, I can see that it picks up the ECS cluster tasks that are in account A, but it doesn't seem to be picking up the ones on account B. Is there any additional configuration steps required for the service in account A to be able to discover the ECS cluster tasks in account B? 

The targets in both accounts are setup correctly to be discovered by the service. I ran the service independently on both accounts and I can see it scrape the targets within the respective account.

Thanks.

**Comment by trallnag** [comment]
Hey @evelez-va, interesting use-case, I've have never considered it. I'd have to do a bit of research. No experience with working across multiple accounts. 

You could check if https://github.com/signal-ai/prometheus-ecs-sd mentions something regarding cross account discovery. PromED is basically a "more refined" version of this project.

Let's say PromED is able to extract targets from other accounts into a file with respective IPs and ports for Prometheus, will Prometheus even be able to scrape the targets? The IPs would have to be public I assume. Or can you map subnets across accounts?

**Comment by evelez-va** [comment]
Hi @trallnag, thanks for the quick response. I'll take a look at that project to see if I find anything. 

We will be setting up VPC peering between account A and B so that Prometheus in A is able to scrape the targets in B (along with the ones in A). In the meantime, I wanted to see if PromED on account A was at least able to discover the the ECS clusters on account B, even if Prometheus can't actually scrape them at the moment (have to wait for procedure for the peering). 

We also considered deploying Prometheus along with PromED on account B like the recommendation, but we wanted to see if it was possible to do it this way and have one Prometheus to monitor our resources on both accounts. Might end up doing it that way if the current approach is not viable.

**Comment by trallnag** [comment]
Okay so I have skipped through a few AWS docs and I don't see why it shouldn't work if the policies and roles are correctly set up. You could test it manually by deploying a task with a single Python container and the role attached you would also use for PromED and then try to use the AWS API like this:

```
import boto3

session = boto3.Session()
ecs = session.client("ecs")
arns = []
for page in ecs.get_paginator(method).paginate("list_clusters", "clusterArns"):
    arns += page.get(key, [])
```

Docs I have read:

* <https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html>
* <https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-cross-account-lambda-auth-and-integration.html>
* <https://docs.aws.amazon.com/AmazonECS/latest/userguide/security-iam.html>

---

Another alternative is to just have PromED in the other account and only connect the Prometheus to the EFS with the file containing the targets.

**Comment by evelez-va** [comment]
Hello, I'm following up with what I found during testing. It seems that in order to be able to discover the ECS targets on another AWS account, the role that grants these permissions has to be explicitly assumed first. You're only able to discover targets within the boundaries of the role that is currently assumed by the EC2 instance. 

In other words, if account A's EC2 role has a policy to assume a the role in account B that grants ECS access, it has to assume the cross account role first before being able to discover targets in account B. It would need an option that allows you to specify which role to use. It doesn't seem like it's possible to do both at the same time without constantly swapping roles (at least, not that I could see). 

For now, I'm using [this](https://github.com/Zomato/prometheus-ecs-discovery) alternative solution which allows for specifying a role, and also custom docker labels (which we needed). I'm running two instances of the service: one in account A to discover local ECS targets, and another specifying it to assume the cross-account role to discover targets in account B. The downside is that this linked repo seems like it hasn't been updated in quite a while.

**Comment by trallnag** [comment]
I see, very interesting. And nice that you have figured a solution that works for you. BTW the project you linked has been updated in June the last time, so not that old I'd argue ;D
